# read  image

In [1]:
#import
import cv2


In [70]:
#version cv2
print(cv2.__version__)

4.7.0


In [71]:
"""
0  grayscale
1  color
-1 alpha channel
"""

'\n0  grayscale\n1  color\n-1 alpha channel\n'

In [72]:
#read image
img= cv2.imread("data/apple.jpg",1)
print(img)

[[[ 90 123 119]
  [ 85 120 116]
  [ 70 111 106]
  ...
  [112 176 164]
  [102 169 154]
  [111 179 162]]

 [[ 80 113 109]
  [ 76 111 107]
  [ 68 109 104]
  ...
  [109 174 159]
  [102 172 155]
  [108 178 161]]

 [[ 80 115 111]
  [ 82 119 115]
  [ 75 116 111]
  ...
  [103 173 156]
  [103 175 155]
  [103 178 157]]

 ...

 [[104 150 108]
  [110 155 112]
  [114 158 111]
  ...
  [106 133 100]
  [106 136 101]
  [108 139 102]]

 [[109 154 115]
  [114 159 116]
  [125 167 120]
  ...
  [109 138  99]
  [105 137  96]
  [109 144 100]]

 [[113 158 119]
  [110 152 111]
  [121 160 114]
  ...
  [128 156 113]
  [121 154 109]
  [114 150 103]]]


In [73]:
import numpy as np

In [ ]:
#show image
for v in range(10):
    for i in range(len(img)):
        for j in range(len(img)):
            img[i][j]=np.random.randint(-250,250,3)
    cv2.imshow("apple",img)
    k=cv2.waitKey(0)
    if k ==27:
        cv2.destroyAllWindows()

In [78]:
img[1][2]

array([101,  45, 184], dtype=uint8)